Add 'linter-swiftlint.additionalOptions' configuration
AtomLinter/linter-swiftlint pull request #40
Opened 2017-01-15 09:34 UTC by norio-nomura

2017-01-17 22:43 UTC, Arcanemagus requested changes

2017-01-17 22:43 UTC, Arcanemagus commented on lib/init.coffee
> +      title: 'additional options to SwiftLint\'s `lint` command
This should be a `description`, not `title` (yes, all the other options are wrong... 😛).

2017-01-17 22:43 UTC, Arcanemagus commented on lib/init.coffee
> +      title: 'additional options to SwiftLint\'s `lint` command
Also, remove the newline from the middle of the string (eg. by concatenation)

2017-01-17 22:44 UTC, Arcanemagus commented
@keplersj Any objection to adding @norio-nomura as a collaborator on here?

Assuming that is something you would want @norio-nomura 😉

2017-01-18 18:21 UTC, keplersj commented
@Arcanemagus I think that's a very good idea and I've offered it to @norio-nomura [before](https://github.com/AtomLinter/linter-swiftlint/pull/8#issuecomment-172714637).

2017-01-18 18:39 UTC, Arcanemagus commented
Ah, good to know lol.

2017-01-24 01:43 UTC, norio-nomura commented
Thank you for offering again.
I didn't think I want to be a collaborator on here. Even though my way of contribution will not change with that, I should accept that as long as I look at `git blame`.

2017-01-24 18:30 UTC, Arcanemagus requested changes

2017-01-24 18:30 UTC, Arcanemagus commented on lib/init.coffee
> +      title: 'Configuration Path'
Atom should default to this title, is it not?

2017-01-24 18:30 UTC, Arcanemagus commented on lib/init.coffee
> +      title: 'Additional Options'
Same with this one. Atom generates a title based on the option name, capitalizing the first letter, and inserting a space whenever it finds a capital letter. So `additionalOptions` _should_ automatically be being translated into `Additional Options`.

2017-01-26 21:44 UTC, Arcanemagus approved these changes
LGTM

2017-01-26 21:45 UTC, Arcanemagus commented
This works as is as far as I'm concerned, the only thing I can think about as far as this PR is concerned is adding a check to make sure the user hasn't specified `--config` in there.

Good to merge @keplersj?

2017-01-27 07:15 UTC, merged

2017-01-27 09:53 UTC, norio-nomura commented
Thanks! 🙏

2017-01-27 16:59 UTC, Arcanemagus commented
Published in v1.2.0. 🎉